/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const MisskeyGlobalContext: typeof import('./hooks/use-misskey-global')['MisskeyGlobalContext']
  const QueryClient: typeof import('@tanstack/react-query')['QueryClient']
  const QueryClientProvider: typeof import('@tanstack/react-query')['QueryClientProvider']
  const cn: typeof import('./lib/utils')['cn']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const getUserSite: typeof import('./services/use-misskey-api')['getUserSite']
  const getUserSiteOrNull: typeof import('./services/use-misskey-api')['getUserSiteOrNull']
  const getUserTokenOrNull: typeof import('./services/use-misskey-api')['getUserTokenOrNull']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const storeUserSite: typeof import('./services/use-misskey-api')['storeUserSite']
  const storeUserToken: typeof import('./services/use-misskey-api')['storeUserToken']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useDeleteNoteAction: typeof import('./hooks/note-actions')['useDeleteNoteAction']
  const useEffect: typeof import('react')['useEffect']
  const useGlobalTimeline: typeof import('./hooks/use-timeline')['useGlobalTimeline']
  const useHomeTimeline: typeof import('./hooks/use-timeline')['useHomeTimeline']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInfiniteQuery: typeof import('@tanstack/react-query')['useInfiniteQuery']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useIsMobile: typeof import('./hooks/use-mobile')['useIsMobile']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMisskeyApi: typeof import('./services/use-misskey-api')['useMisskeyApi']
  const useMisskeyGlobal: typeof import('./hooks/use-misskey-global')['useMisskeyGlobal']
  const useMisskeyStream: typeof import('./services/use-misskey-api')['useMisskeyStream']
  const useMutation: typeof import('@tanstack/react-query')['useMutation']
  const useNavigate: typeof import('@tanstack/react-router')['useNavigate']
  const useParams: typeof import('@tanstack/react-router')['useParams']
  const useQuery: typeof import('@tanstack/react-query')['useQuery']
  const useQueryClient: typeof import('@tanstack/react-query')['useQueryClient']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRenoteAction: typeof import('./hooks/note-actions')['useRenoteAction']
  const useRouter: typeof import('@tanstack/react-router')['useRouter']
  const useSearch: typeof import('@tanstack/react-router')['useSearch']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTimeline: typeof import('./hooks/use-timeline')['useTimeline']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
  const useUnrenoteAction: typeof import('./hooks/note-actions')['useUnrenoteAction']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MisskeyGlobalContextType } from './hooks/use-misskey-global'
  import('./hooks/use-misskey-global')
  // @ts-ignore
  export type { TimelineTypes } from './hooks/use-timeline'
  import('./hooks/use-timeline')
  // @ts-ignore
  export type { NoteWithExtension } from './types/note'
  import('./types/note')
}
