/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PostingRouteImport } from './routes/posting'
import { Route as LoginRedirectRouteImport } from './routes/login-redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AccountSwitchRouteImport } from './routes/account-switch'
import { Route as AtChar123acctChar125RouteImport } from './routes/@{$acct}'
import { Route as MissingRouteImport } from './routes/$missing'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as TimelineRouteRouteImport } from './routes/_timeline/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TimelineIndexRouteImport } from './routes/_timeline/index'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPageRouteImport } from './routes/settings/$page'
import { Route as NotesIdRouteImport } from './routes/notes/$id'
import { Route as MyFavoritesRouteImport } from './routes/my/favorites'
import { Route as MyClipsRouteImport } from './routes/my/clips'
import { Route as ClipsIdRouteImport } from './routes/clips/$id'
import { Route as TimelineLocalTimelineRouteImport } from './routes/_timeline/local-timeline'
import { Route as TimelineHybridTimelineRouteImport } from './routes/_timeline/hybrid-timeline'
import { Route as TimelineGlobalTimelineRouteImport } from './routes/_timeline/global-timeline'
import { Route as MyNotificationsRouteRouteImport } from './routes/my/notifications/route'
import { Route as MyFollowRequestsRouteRouteImport } from './routes/my/follow-requests/route'
import { Route as MyNotificationsIndexRouteImport } from './routes/my/notifications/index'
import { Route as MyDriveIndexRouteImport } from './routes/my/drive/index'
import { Route as MyNotificationsPmRouteImport } from './routes/my/notifications/pm'
import { Route as MyNotificationsMentionsRouteImport } from './routes/my/notifications/mentions'
import { Route as MyFollowRequestsSentRouteImport } from './routes/my/follow-requests/sent'
import { Route as MyFollowRequestsReceivedRouteImport } from './routes/my/follow-requests/received'
import { Route as MyDriveFolderFolderRouteImport } from './routes/my/drive/folder/$folder'
import { Route as MyDriveFileFileRouteImport } from './routes/my/drive/file/$file'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PostingRoute = PostingRouteImport.update({
  id: '/posting',
  path: '/posting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRedirectRoute = LoginRedirectRouteImport.update({
  id: '/login-redirect',
  path: '/login-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSwitchRoute = AccountSwitchRouteImport.update({
  id: '/account-switch',
  path: '/account-switch',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123acctChar125Route = AtChar123acctChar125RouteImport.update({
  id: '/@{$acct}',
  path: '/@{$acct}',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingRoute = MissingRouteImport.update({
  id: '/$missing',
  path: '/$missing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRouteRoute = TimelineRouteRouteImport.update({
  id: '/_timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimelineRouteRoute,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPageRoute = SettingsPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFavoritesRoute = MyFavoritesRouteImport.update({
  id: '/my/favorites',
  path: '/my/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClipsRoute = MyClipsRouteImport.update({
  id: '/my/clips',
  path: '/my/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsIdRoute = ClipsIdRouteImport.update({
  id: '/clips/$id',
  path: '/clips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineLocalTimelineRoute = TimelineLocalTimelineRouteImport.update({
  id: '/local-timeline',
  path: '/local-timeline',
  getParentRoute: () => TimelineRouteRoute,
} as any)
const TimelineHybridTimelineRoute = TimelineHybridTimelineRouteImport.update({
  id: '/hybrid-timeline',
  path: '/hybrid-timeline',
  getParentRoute: () => TimelineRouteRoute,
} as any)
const TimelineGlobalTimelineRoute = TimelineGlobalTimelineRouteImport.update({
  id: '/global-timeline',
  path: '/global-timeline',
  getParentRoute: () => TimelineRouteRoute,
} as any)
const MyNotificationsRouteRoute = MyNotificationsRouteRouteImport.update({
  id: '/my/notifications',
  path: '/my/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFollowRequestsRouteRoute = MyFollowRequestsRouteRouteImport.update({
  id: '/my/follow-requests',
  path: '/my/follow-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNotificationsIndexRoute = MyNotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyNotificationsRouteRoute,
} as any)
const MyDriveIndexRoute = MyDriveIndexRouteImport.update({
  id: '/my/drive/',
  path: '/my/drive/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNotificationsPmRoute = MyNotificationsPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => MyNotificationsRouteRoute,
} as any)
const MyNotificationsMentionsRoute = MyNotificationsMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => MyNotificationsRouteRoute,
} as any)
const MyFollowRequestsSentRoute = MyFollowRequestsSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => MyFollowRequestsRouteRoute,
} as any)
const MyFollowRequestsReceivedRoute =
  MyFollowRequestsReceivedRouteImport.update({
    id: '/received',
    path: '/received',
    getParentRoute: () => MyFollowRequestsRouteRoute,
  } as any)
const MyDriveFolderFolderRoute = MyDriveFolderFolderRouteImport.update({
  id: '/my/drive/folder/$folder',
  path: '/my/drive/folder/$folder',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDriveFileFileRoute = MyDriveFileFileRouteImport.update({
  id: '/my/drive/file/$file',
  path: '/my/drive/file/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$missing': typeof MissingRoute
  '/@{$acct}': typeof AtChar123acctChar125Route
  '/account-switch': typeof AccountSwitchRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/login-redirect': typeof LoginRedirectRoute
  '/posting': typeof PostingRoute
  '/search': typeof SearchRoute
  '/my/follow-requests': typeof MyFollowRequestsRouteRouteWithChildren
  '/my/notifications': typeof MyNotificationsRouteRouteWithChildren
  '/global-timeline': typeof TimelineGlobalTimelineRoute
  '/hybrid-timeline': typeof TimelineHybridTimelineRoute
  '/local-timeline': typeof TimelineLocalTimelineRoute
  '/clips/$id': typeof ClipsIdRoute
  '/my/clips': typeof MyClipsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/notes/$id': typeof NotesIdRoute
  '/settings/$page': typeof SettingsPageRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tag': typeof TagTagRoute
  '/': typeof TimelineIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/my/follow-requests/received': typeof MyFollowRequestsReceivedRoute
  '/my/follow-requests/sent': typeof MyFollowRequestsSentRoute
  '/my/notifications/mentions': typeof MyNotificationsMentionsRoute
  '/my/notifications/pm': typeof MyNotificationsPmRoute
  '/my/drive': typeof MyDriveIndexRoute
  '/my/notifications/': typeof MyNotificationsIndexRoute
  '/my/drive/file/$file': typeof MyDriveFileFileRoute
  '/my/drive/folder/$folder': typeof MyDriveFolderFolderRoute
}
export interface FileRoutesByTo {
  '/$missing': typeof MissingRoute
  '/@{$acct}': typeof AtChar123acctChar125Route
  '/account-switch': typeof AccountSwitchRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/login-redirect': typeof LoginRedirectRoute
  '/posting': typeof PostingRoute
  '/search': typeof SearchRoute
  '/my/follow-requests': typeof MyFollowRequestsRouteRouteWithChildren
  '/global-timeline': typeof TimelineGlobalTimelineRoute
  '/hybrid-timeline': typeof TimelineHybridTimelineRoute
  '/local-timeline': typeof TimelineLocalTimelineRoute
  '/clips/$id': typeof ClipsIdRoute
  '/my/clips': typeof MyClipsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/notes/$id': typeof NotesIdRoute
  '/settings/$page': typeof SettingsPageRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tag': typeof TagTagRoute
  '/': typeof TimelineIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/my/follow-requests/received': typeof MyFollowRequestsReceivedRoute
  '/my/follow-requests/sent': typeof MyFollowRequestsSentRoute
  '/my/notifications/mentions': typeof MyNotificationsMentionsRoute
  '/my/notifications/pm': typeof MyNotificationsPmRoute
  '/my/drive': typeof MyDriveIndexRoute
  '/my/notifications': typeof MyNotificationsIndexRoute
  '/my/drive/file/$file': typeof MyDriveFileFileRoute
  '/my/drive/folder/$folder': typeof MyDriveFolderFolderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_timeline': typeof TimelineRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$missing': typeof MissingRoute
  '/@{$acct}': typeof AtChar123acctChar125Route
  '/account-switch': typeof AccountSwitchRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/login-redirect': typeof LoginRedirectRoute
  '/posting': typeof PostingRoute
  '/search': typeof SearchRoute
  '/my/follow-requests': typeof MyFollowRequestsRouteRouteWithChildren
  '/my/notifications': typeof MyNotificationsRouteRouteWithChildren
  '/_timeline/global-timeline': typeof TimelineGlobalTimelineRoute
  '/_timeline/hybrid-timeline': typeof TimelineHybridTimelineRoute
  '/_timeline/local-timeline': typeof TimelineLocalTimelineRoute
  '/clips/$id': typeof ClipsIdRoute
  '/my/clips': typeof MyClipsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/notes/$id': typeof NotesIdRoute
  '/settings/$page': typeof SettingsPageRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tag': typeof TagTagRoute
  '/_timeline/': typeof TimelineIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/my/follow-requests/received': typeof MyFollowRequestsReceivedRoute
  '/my/follow-requests/sent': typeof MyFollowRequestsSentRoute
  '/my/notifications/mentions': typeof MyNotificationsMentionsRoute
  '/my/notifications/pm': typeof MyNotificationsPmRoute
  '/my/drive/': typeof MyDriveIndexRoute
  '/my/notifications/': typeof MyNotificationsIndexRoute
  '/my/drive/file/$file': typeof MyDriveFileFileRoute
  '/my/drive/folder/$folder': typeof MyDriveFolderFolderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/$missing'
    | '/@{$acct}'
    | '/account-switch'
    | '/announcements'
    | '/chat'
    | '/login'
    | '/login-redirect'
    | '/posting'
    | '/search'
    | '/my/follow-requests'
    | '/my/notifications'
    | '/global-timeline'
    | '/hybrid-timeline'
    | '/local-timeline'
    | '/clips/$id'
    | '/my/clips'
    | '/my/favorites'
    | '/notes/$id'
    | '/settings/$page'
    | '/settings/profile'
    | '/tag/$tag'
    | '/'
    | '/settings/'
    | '/my/follow-requests/received'
    | '/my/follow-requests/sent'
    | '/my/notifications/mentions'
    | '/my/notifications/pm'
    | '/my/drive'
    | '/my/notifications/'
    | '/my/drive/file/$file'
    | '/my/drive/folder/$folder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$missing'
    | '/@{$acct}'
    | '/account-switch'
    | '/announcements'
    | '/chat'
    | '/login'
    | '/login-redirect'
    | '/posting'
    | '/search'
    | '/my/follow-requests'
    | '/global-timeline'
    | '/hybrid-timeline'
    | '/local-timeline'
    | '/clips/$id'
    | '/my/clips'
    | '/my/favorites'
    | '/notes/$id'
    | '/settings/$page'
    | '/settings/profile'
    | '/tag/$tag'
    | '/'
    | '/settings'
    | '/my/follow-requests/received'
    | '/my/follow-requests/sent'
    | '/my/notifications/mentions'
    | '/my/notifications/pm'
    | '/my/drive'
    | '/my/notifications'
    | '/my/drive/file/$file'
    | '/my/drive/folder/$folder'
  id:
    | '__root__'
    | '/_timeline'
    | '/settings'
    | '/$missing'
    | '/@{$acct}'
    | '/account-switch'
    | '/announcements'
    | '/chat'
    | '/login'
    | '/login-redirect'
    | '/posting'
    | '/search'
    | '/my/follow-requests'
    | '/my/notifications'
    | '/_timeline/global-timeline'
    | '/_timeline/hybrid-timeline'
    | '/_timeline/local-timeline'
    | '/clips/$id'
    | '/my/clips'
    | '/my/favorites'
    | '/notes/$id'
    | '/settings/$page'
    | '/settings/profile'
    | '/tag/$tag'
    | '/_timeline/'
    | '/settings/'
    | '/my/follow-requests/received'
    | '/my/follow-requests/sent'
    | '/my/notifications/mentions'
    | '/my/notifications/pm'
    | '/my/drive/'
    | '/my/notifications/'
    | '/my/drive/file/$file'
    | '/my/drive/folder/$folder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TimelineRouteRoute: typeof TimelineRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  MissingRoute: typeof MissingRoute
  AtChar123acctChar125Route: typeof AtChar123acctChar125Route
  AccountSwitchRoute: typeof AccountSwitchRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  LoginRedirectRoute: typeof LoginRedirectRoute
  PostingRoute: typeof PostingRoute
  SearchRoute: typeof SearchRoute
  MyFollowRequestsRouteRoute: typeof MyFollowRequestsRouteRouteWithChildren
  MyNotificationsRouteRoute: typeof MyNotificationsRouteRouteWithChildren
  ClipsIdRoute: typeof ClipsIdRoute
  MyClipsRoute: typeof MyClipsRoute
  MyFavoritesRoute: typeof MyFavoritesRoute
  NotesIdRoute: typeof NotesIdRoute
  TagTagRoute: typeof TagTagRoute
  MyDriveIndexRoute: typeof MyDriveIndexRoute
  MyDriveFileFileRoute: typeof MyDriveFileFileRoute
  MyDriveFolderFolderRoute: typeof MyDriveFolderFolderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posting': {
      id: '/posting'
      path: '/posting'
      fullPath: '/posting'
      preLoaderRoute: typeof PostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-redirect': {
      id: '/login-redirect'
      path: '/login-redirect'
      fullPath: '/login-redirect'
      preLoaderRoute: typeof LoginRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-switch': {
      id: '/account-switch'
      path: '/account-switch'
      fullPath: '/account-switch'
      preLoaderRoute: typeof AccountSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$acct}': {
      id: '/@{$acct}'
      path: '/@{$acct}'
      fullPath: '/@{$acct}'
      preLoaderRoute: typeof AtChar123acctChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$missing': {
      id: '/$missing'
      path: '/$missing'
      fullPath: '/$missing'
      preLoaderRoute: typeof MissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timeline': {
      id: '/_timeline'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TimelineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_timeline/': {
      id: '/_timeline/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof TimelineRouteRoute
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/$page': {
      id: '/settings/$page'
      path: '/$page'
      fullPath: '/settings/$page'
      preLoaderRoute: typeof SettingsPageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/favorites': {
      id: '/my/favorites'
      path: '/my/favorites'
      fullPath: '/my/favorites'
      preLoaderRoute: typeof MyFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/clips': {
      id: '/my/clips'
      path: '/my/clips'
      fullPath: '/my/clips'
      preLoaderRoute: typeof MyClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips/$id': {
      id: '/clips/$id'
      path: '/clips/$id'
      fullPath: '/clips/$id'
      preLoaderRoute: typeof ClipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timeline/local-timeline': {
      id: '/_timeline/local-timeline'
      path: '/local-timeline'
      fullPath: '/local-timeline'
      preLoaderRoute: typeof TimelineLocalTimelineRouteImport
      parentRoute: typeof TimelineRouteRoute
    }
    '/_timeline/hybrid-timeline': {
      id: '/_timeline/hybrid-timeline'
      path: '/hybrid-timeline'
      fullPath: '/hybrid-timeline'
      preLoaderRoute: typeof TimelineHybridTimelineRouteImport
      parentRoute: typeof TimelineRouteRoute
    }
    '/_timeline/global-timeline': {
      id: '/_timeline/global-timeline'
      path: '/global-timeline'
      fullPath: '/global-timeline'
      preLoaderRoute: typeof TimelineGlobalTimelineRouteImport
      parentRoute: typeof TimelineRouteRoute
    }
    '/my/notifications': {
      id: '/my/notifications'
      path: '/my/notifications'
      fullPath: '/my/notifications'
      preLoaderRoute: typeof MyNotificationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/follow-requests': {
      id: '/my/follow-requests'
      path: '/my/follow-requests'
      fullPath: '/my/follow-requests'
      preLoaderRoute: typeof MyFollowRequestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/notifications/': {
      id: '/my/notifications/'
      path: '/'
      fullPath: '/my/notifications/'
      preLoaderRoute: typeof MyNotificationsIndexRouteImport
      parentRoute: typeof MyNotificationsRouteRoute
    }
    '/my/drive/': {
      id: '/my/drive/'
      path: '/my/drive'
      fullPath: '/my/drive'
      preLoaderRoute: typeof MyDriveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/notifications/pm': {
      id: '/my/notifications/pm'
      path: '/pm'
      fullPath: '/my/notifications/pm'
      preLoaderRoute: typeof MyNotificationsPmRouteImport
      parentRoute: typeof MyNotificationsRouteRoute
    }
    '/my/notifications/mentions': {
      id: '/my/notifications/mentions'
      path: '/mentions'
      fullPath: '/my/notifications/mentions'
      preLoaderRoute: typeof MyNotificationsMentionsRouteImport
      parentRoute: typeof MyNotificationsRouteRoute
    }
    '/my/follow-requests/sent': {
      id: '/my/follow-requests/sent'
      path: '/sent'
      fullPath: '/my/follow-requests/sent'
      preLoaderRoute: typeof MyFollowRequestsSentRouteImport
      parentRoute: typeof MyFollowRequestsRouteRoute
    }
    '/my/follow-requests/received': {
      id: '/my/follow-requests/received'
      path: '/received'
      fullPath: '/my/follow-requests/received'
      preLoaderRoute: typeof MyFollowRequestsReceivedRouteImport
      parentRoute: typeof MyFollowRequestsRouteRoute
    }
    '/my/drive/folder/$folder': {
      id: '/my/drive/folder/$folder'
      path: '/my/drive/folder/$folder'
      fullPath: '/my/drive/folder/$folder'
      preLoaderRoute: typeof MyDriveFolderFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/drive/file/$file': {
      id: '/my/drive/file/$file'
      path: '/my/drive/file/$file'
      fullPath: '/my/drive/file/$file'
      preLoaderRoute: typeof MyDriveFileFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TimelineRouteRouteChildren {
  TimelineGlobalTimelineRoute: typeof TimelineGlobalTimelineRoute
  TimelineHybridTimelineRoute: typeof TimelineHybridTimelineRoute
  TimelineLocalTimelineRoute: typeof TimelineLocalTimelineRoute
  TimelineIndexRoute: typeof TimelineIndexRoute
}

const TimelineRouteRouteChildren: TimelineRouteRouteChildren = {
  TimelineGlobalTimelineRoute: TimelineGlobalTimelineRoute,
  TimelineHybridTimelineRoute: TimelineHybridTimelineRoute,
  TimelineLocalTimelineRoute: TimelineLocalTimelineRoute,
  TimelineIndexRoute: TimelineIndexRoute,
}

const TimelineRouteRouteWithChildren = TimelineRouteRoute._addFileChildren(
  TimelineRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsPageRoute: typeof SettingsPageRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsPageRoute: SettingsPageRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface MyFollowRequestsRouteRouteChildren {
  MyFollowRequestsReceivedRoute: typeof MyFollowRequestsReceivedRoute
  MyFollowRequestsSentRoute: typeof MyFollowRequestsSentRoute
}

const MyFollowRequestsRouteRouteChildren: MyFollowRequestsRouteRouteChildren = {
  MyFollowRequestsReceivedRoute: MyFollowRequestsReceivedRoute,
  MyFollowRequestsSentRoute: MyFollowRequestsSentRoute,
}

const MyFollowRequestsRouteRouteWithChildren =
  MyFollowRequestsRouteRoute._addFileChildren(
    MyFollowRequestsRouteRouteChildren,
  )

interface MyNotificationsRouteRouteChildren {
  MyNotificationsMentionsRoute: typeof MyNotificationsMentionsRoute
  MyNotificationsPmRoute: typeof MyNotificationsPmRoute
  MyNotificationsIndexRoute: typeof MyNotificationsIndexRoute
}

const MyNotificationsRouteRouteChildren: MyNotificationsRouteRouteChildren = {
  MyNotificationsMentionsRoute: MyNotificationsMentionsRoute,
  MyNotificationsPmRoute: MyNotificationsPmRoute,
  MyNotificationsIndexRoute: MyNotificationsIndexRoute,
}

const MyNotificationsRouteRouteWithChildren =
  MyNotificationsRouteRoute._addFileChildren(MyNotificationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TimelineRouteRoute: TimelineRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  MissingRoute: MissingRoute,
  AtChar123acctChar125Route: AtChar123acctChar125Route,
  AccountSwitchRoute: AccountSwitchRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  LoginRedirectRoute: LoginRedirectRoute,
  PostingRoute: PostingRoute,
  SearchRoute: SearchRoute,
  MyFollowRequestsRouteRoute: MyFollowRequestsRouteRouteWithChildren,
  MyNotificationsRouteRoute: MyNotificationsRouteRouteWithChildren,
  ClipsIdRoute: ClipsIdRoute,
  MyClipsRoute: MyClipsRoute,
  MyFavoritesRoute: MyFavoritesRoute,
  NotesIdRoute: NotesIdRoute,
  TagTagRoute: TagTagRoute,
  MyDriveIndexRoute: MyDriveIndexRoute,
  MyDriveFileFileRoute: MyDriveFileFileRoute,
  MyDriveFolderFolderRoute: MyDriveFolderFolderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
